### ISSUE TITLE
Crash When Using The Speed Command

### ISSUE THREAD

**Issue by 0H4rl3qu1n0** [Maciej916/Ma-Essentials#22]
**Describe the bug**
When i did the /speed command The server crashed.

**How to reproduce**
Load the server
do /speed

Error:
java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerAbilities.func_195931_a(F)V
        at com.maciej916.maessentials.commands.CommandSpeed.doSpeed(CommandSpeed.java:60) ~[?:1.14.4-1.2.5] {re:classloading}
        at com.maciej916.maessentials.commands.CommandSpeed.speedArgs(CommandSpeed.java:42) ~[?:1.14.4-1.2.5] {re:classloading}
        at com.maciej916.maessentials.commands.CommandSpeed.lambda$register$2(CommandSpeed.java:26) ~[?:1.14.4-1.2.5] {re:classloading}
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[?:?] {re:classloading}
        at net.minecraft.command.Commands.func_197059_a(Commands.java:194) ~[?:?] {re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:981) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:964) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:37) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221] {}
[m[1;31m[12:10:01] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\0derp\Desktop\Soup\ATM4\.\crash-reports\crash-2019-12-05_12.10.01-server.txt

**Expected behavior**
Giving me speed 10

**Versions**
- **Ma Essentials**: 1.2.5
- **Forge**: 28.1.96

**Comment by lukasdeveloper** [comment]
I have the same issue.

**Comment by Maciej916** [comment]
Added temporary fix in [v1.2.7](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/2843699)

**Comment by Maciej916** [comment]
Fixed in [1.14.4 v1.2.8](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/2848871)
